apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: hse-coursework-health
  labels:
    app: redis
spec:
  type: ClusterIP            # внутренний сервис
  selector:
    app: redis               # совпадает с matchLabels в Deployment
  ports:
    - name: redis
      port: 6379             # порт внутри кластера
      targetPort: 6379       # порт в контейнере
